"""Wire contracts for the REST API, one module per resource.

Re-exported here so call sites import from ``app.schemas`` and are unaffected when a
contract moves between modules.
"""

from app.schemas.application import (
    ApplicationCreateRequest,
    ApplicationDetail,
    ApplicationEventOut,
    ApplicationMoveRequest,
    ApplicationOut,
    ApplicationRow,
    PipelineOut,
)
from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse, UserOut
from app.schemas.candidate import (
    BestMatchOut,
    JobMatchOut,
    CandidateDetailResponse,
    CandidateListItem,
    CandidateListResponse,
    CandidateOut,
    CandidateSummary,
    CandidateUpdateRequest,
    ProfileOut,
)
from app.schemas.chat import (
    ChatMessageOut,
    ChatReply,
    ChatRequest,
    ConversationDetail,
    ConversationOut,
    ToolCallOut,
)
from app.schemas.common import ORMModel
from app.schemas.dashboard import (
    ActivityItemOut,
    AttentionItemOut,
    DashboardResponse,
    DayActivityOut,
    DayCountOut,
    JobCardOut,
    MatchedCandidateOut,
    MetricOut,
    OpenJobRowOut,
    RecentCandidateOut,
    ReviewCandidateOut,
    RoleSliceOut,
)
from app.schemas.interview import (
    InterviewCreateRequest,
    InterviewListResponse,
    InterviewOut,
    InterviewUpdateRequest,
)
from app.schemas.job import (
    JobCreateRequest,
    JobDetailResponse,
    JobListItem,
    JobOut,
    JobStatsOut,
    JobUpdateRequest,
    RequirementOut,
    SkillCoverageOut,
)
from app.schemas.matching import (
    ExplanationOut,
    FunnelOut,
    OverrideRequest,
    RankedCandidateOut,
    ScreeningCreateRequest,
    ScreeningOut,
    ScreeningResultsResponse,
    ScreeningStatusResponse,
    SearchCandidateOut,
    SearchCreateRequest,
    SearchPageResponse,
    SubscoreOut,
)
from app.schemas.resume import (
    RejectedUpload,
    ResumeOut,
    ResumeStatusOut,
    UploadAccepted,
)

__all__ = [
    "ApplicationCreateRequest",
    "ApplicationDetail",
    "ApplicationEventOut",
    "ApplicationMoveRequest",
    "ApplicationOut",
    "ApplicationRow",
    "PipelineOut",
    "BestMatchOut",
    "JobMatchOut",
    "CandidateDetailResponse",
    "CandidateUpdateRequest",
    "CandidateListItem",
    "CandidateListResponse",
    "CandidateOut",
    "CandidateSummary",
    "ChatMessageOut",
    "ChatReply",
    "ChatRequest",
    "ConversationDetail",
    "ConversationOut",
    "ActivityItemOut",
    "AttentionItemOut",
    "DashboardResponse",
    "DayActivityOut",
    "DayCountOut",
    "ExplanationOut",
    "FunnelOut",
    "InterviewCreateRequest",
    "InterviewListResponse",
    "InterviewOut",
    "InterviewUpdateRequest",
    "JobCreateRequest",
    "JobDetailResponse",
    "JobStatsOut",
    "JobUpdateRequest",
    "SkillCoverageOut",
    "JobCardOut",
    "JobListItem",
    "JobOut",
    "LoginRequest",
    "MatchedCandidateOut",
    "MetricOut",
    "OpenJobRowOut",
    "ReviewCandidateOut",
    "ORMModel",
    "OverrideRequest",
    "ProfileOut",
    "RegisterRequest",
    "RankedCandidateOut",
    "RejectedUpload",
    "RecentCandidateOut",
    "RequirementOut",
    "RoleSliceOut",
    "ResumeOut",
    "ResumeStatusOut",
    "ScreeningCreateRequest",
    "ScreeningOut",
    "ScreeningResultsResponse",
    "ScreeningStatusResponse",
    "SearchCandidateOut",
    "SearchCreateRequest",
    "SearchPageResponse",
    "SubscoreOut",
    "TokenResponse",
    "ToolCallOut",
    "UploadAccepted",
    "UserOut",
]
