"""applications, interviews, job and candidate fields

Revision ID: cd26d9d40cd8
Revises: 0004
Create Date: 2026-09-08 13:59:12.574191
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # NOTE: ix_profiles_skills_gin and ix_embeddings_vector_hnsw are raw-SQL
    # indexes from 0001. Autogenerate cannot see them and proposes dropping them
    # on every revision; dropping the HNSW one turns retrieval into a sequential
    # scan. Third time this has come up — left alone deliberately.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('origin_screening_result_id', sa.UUID(), nullable=True),
    sa.Column('match_score_at_entry', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_screening_result_id'], ['screening_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_application_candidate_job')
    )
    op.create_index('ix_applications_candidate', 'applications', ['candidate_id'], unique=False)
    op.create_index('ix_applications_job_stage', 'applications', ['job_id', 'stage'], unique=False)
    op.create_index(op.f('ix_applications_stage'), 'applications', ['stage'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=24), nullable=True),
    sa.Column('to_stage', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_events_application', 'application_events', ['application_id', 'created_at'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=True),
    sa.Column('interviewer', sa.String(length=160), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_scheduled', 'interviews', ['scheduled_at'], unique=False)
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(length=320), nullable=True))
    op.add_column('candidates', sa.Column('availability_days', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('expected_salary', sa.String(length=80), nullable=True))
    op.add_column('jobs', sa.Column('department', sa.String(length=120), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=60), nullable=True))
    op.add_column('jobs', sa.Column('hiring_manager', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'hiring_manager')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'department')
    op.drop_column('candidates', 'expected_salary')
    op.drop_column('candidates', 'availability_days')
    op.drop_column('candidates', 'linkedin_url')
    op.drop_index('ix_interviews_scheduled', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('ix_app_events_application', table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_stage'), table_name='applications')
    op.drop_index('ix_applications_job_stage', table_name='applications')
    op.drop_index('ix_applications_candidate', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
